
CREATE TABLE IF NOT EXISTS `NodeInfo` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	Path TEXT NOT NULL UNIQUE,
	LastChecked INT UNSIGNED NOT NULL DEFAULT 0,
	Type CHAR(10) NOT NULL,
	UID INT UNSIGNED NOT NULL,
	GID INT UNSIGNED NOT NULL,
	Links INT UNSIGNED NOT NULL,
	Inode INT UNSIGNED NOT NULL,
	Perms CHAR(10),
	CTime INT UNSIGNED NOT NULL,
	Size INT UNSIGNED,
	SHA1 CHAR(40),
	LinkDest TEXT
);
CREATE INDEX NodeInfo_Path ON NodeInfo(Path);
CREATE INDEX NodeInfo_LastChecked ON NodeInfo(LastChecked);

CREATE TABLE IF NOT EXISTS `Report` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	Path TEXT NOT NULL,
	Notes TEXT NOT NULL,
	Time INT UNSIGNED NOT NULL DEFAULT 0
);
/*CREATE INDEX Report_Time ON Report(Time);*/

CREATE TABLE IF NOT EXISTS `LogPosition` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	LogFile TEXT NOT NULL UNIQUE,
	Inode INT UNSIGNED NOT NULL,
	Position INT UNSIGNED NOT NULL
);
CREATE INDEX LogPosition_LogFile ON LogPosition(LogFile);
CREATE TABLE IF NOT EXISTS `LogReport` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	LogFile TEXT NOT NULL,
	Line TEXT NOT NULL,
	Priority CHAR(20) NOT NULL,
	Time INT UNSIGNED NOT NULL DEFAULT 0
);
CREATE INDEX LogReport_Priority ON LogReport(Priority);


/* TODO */
CREATE TABLE IF NOT EXISTS `PID` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	File TEXT NOT NULL,
	HostPID INT UNSIGNED NOT NULL,
	CT INT UNSIGNED NOT NULL,
	CTPID INT UNSIGNED NOT NULL,
	PidFileExists BOOL NOT NULL,
	Alive BOOL NOT NULL,
	LastChecked INT UNSIGNED NOT NULL DEFAULT 0
);
CREATE INDEX PID_File ON PID(File);
CREATE TABLE IF NOT EXISTS `PIDReport` (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	File TEXT NOT NULL,
	Notes TEXT NOT NULL,
	Time INT UNSIGNED NOT NULL
);

